services:
  traefik:
    image: traefik:v3.5
    container_name: traefik-internal
    networks:
      - traefik_internal
      - internal_web
    depends_on:
      - traefik-internal-redis
    ports:
      - "80:80"
      - "443:443"
      # - "8180:8080"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    volumes:
      - ./traefik/letsencrypt:/letsencrypt
      - ./traefik/certificates:/certificates
      - ./traefik/log:/var/log/traefik:rw
      - ./traefik/static-config/traefik.yml:/etc/traefik/traefik.yml:rw
      - ./traefik/dynamic-config:/config/dynamic:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-dashboard-internal.rule: Host(`traefik-internal.<PUBLICDOMAIN1>`)
      traefik.http.routers.traefik-dashboard-internal.service: api@internal
      traefik.docker.network: internal_web
      kop.namespace: internal

  logrotate:
    image: vegardit/traefik-logrotate:latest
    container_name: traefik-internal-logrotate
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw # required to send USR1 signal to Traefik after log rotation
      - ./traefik/log:/var/log/traefik:rw # folder containing access.log file
    environment:
      TZ: "America/Los_Angeles"
      # all environment variables are optional and show the default values:
      LOGROTATE_LOGS: "/var/log/traefik/*.log" # log files to rotate, directory must match volume mount
      LOGROTATE_TRIGGER_INTERVAL: daily  # rotate daily, must be one of: daily, weekly, monthly, yearly
      LOGROTATE_TRIGGER_SIZE: 50M        # rotate if log file size reaches 50MB
      LOGROTATE_MAX_BACKUPS: 7          # keep 14 backup copies per rotated log file
      LOGROTATE_START_INDEX: 1           # first rotated file is called access.1.log
      LOGROTATE_FILE_MODE: 0644          # file mode of the rotated file
      LOGROTATE_FILE_USER: root          # owning user of the rotated file
      LOGROTATE_FILE_GROUP: root         # owning group of the rotated file
      CRON_SCHEDULE: "* * * * *"
      CRON_LOG_LEVEL: 8                  # see https://unix.stackexchange.com/a/414010/378036
      # command to determine the id of the container running Traefik:
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --no-trunc --quiet --filter label=org.opencontainers.image.title=Traefik

  traefik-access-logs:
    image: alpine
    container_name: traefik-internal-access-logs
    volumes:
      - ./traefik/log:/var/log:ro
    command: >
      sh -c "tail -F /var/log/access.log"
    network_mode: none
    restart: unless-stopped
    
  traefik-internal-redis:
    restart: unless-stopped
    image: redis:7-alpine
    container_name: traefik-internal-redis
    # ports:
    #   - "6379:6379"
    networks:
      - traefik_internal
      - kop_net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  logdy:
    build:
      context: https://github.com/logdyhq/logdy-core.git
    read_only: true
    container_name: traefik-internal-logs
    networks:
      - internal_web
      - traefik_internal
    volumes:
      - ./traefik/log:/var/log:ro
      - ./logdy/logdy.json:/config/logdy.json
    command:
      - "--config"
      - "/config/logdy.json"
      - "follow"
      #- "--full-read"
      - "/var/log/access.log"
      - "--no-analytics"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    labels:
      traefik.enable: true
      traefik.http.routers.logdy-traefik-internal.rule: Host(`traefik-log-internal.<PUBLICDOMAIN1>`)
      traefik.http.services.logdy-traefik-internal.loadbalancer.server.port: 8080
      traefik.docker.network: internal_web
      kop.namespace: internal

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
    networks:
      - internal_web
      - traefik_internal
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`whoami.<PUBLICDOMAIN1>`)
      traefik.docker.network: internal_web
      kop.namespace: internal

networks:
  traefik_internal:
    external: true
  kop_net:
    external: true
  internal_web:
    external: true
