services:
  traefik-kop-public:
    image: "ghcr.io/jittering/traefik-kop:latest"
    container_name: traefik-kop-public
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=traefik-external-redis:6379"
      - "NAMESPACE=public"
      - "DOCKER_HOST=tcp://socket-proxy:2375"
      - "KOP_HOSTNAME=${HOSTNAME:-generic}-public"
      - "BIND_IP=${BIND_IP}"
    depends_on:
      - socket-proxy
    networks:
      - default
      - kop_net

  traefik-kop-internal:
    image: "ghcr.io/jittering/traefik-kop:latest"
    container_name: traefik-kop-internal
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=traefik-internal-redis:6379"
      - "NAMESPACE=internal"
      - "DOCKER_HOST=tcp://socket-proxy:2375"
      - "KOP_HOSTNAME=${HOSTNAME:-generic}-internal"
      - "BIND_IP=${BIND_IP}"
    depends_on:
      - socket-proxy
    networks:
      - default
      - kop_net
      
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: traefik-kop-socket-proxy
    networks:
      - default
    environment:
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
      - POST=0
      - SERVICES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run

networks:
  kop_net:
    external: true
